server:
  address: 127.0.0.1
  port: 19090

### DataBase Config
spring:
  datasource:
    url: 'jdbc:mysql://172.16.1.254:3306/mini_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true'
    username: root
    password: u2FsdGVkX1VV7V%222aNySZq&

### Mybatis Config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
